# Generated by Django 5.2.1 on 2025-10-27 11:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeese', '0002_rename_employee_employeese_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employeese_employee',
            new_name='Employee',
        ),
    ]
