# Generated by Django 5.2.1 on 2025-11-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeese', '0005_employee_department_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
